#pragma once
#define GAME_TITLE "GTA2"

#define GAME_MAJOR_VERSION 0
#define GAME_MINOR_VERSION 0
#define GAME_BUILD_VERSION 1

#define GAME_VERSION_STRING (GAME_MAJOR_VERSION + "." + GAME_MINOR_VERSION + "." + GAME_BUILD_VERSION)

#define SETTINGS_VERSION_STRING "1.0"
